### ISSUE TITLE
 Поток <utils.blum.Start object at 0x0000024403A68380> | Ошибка: unsupported operand type(s) for /: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by whatever193** [MalinovyjMakintosh/Blum_software#2]
Поток <utils.blum.Start object at 0x0000024403A68380> | Ошибка: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by MalinovyjMakintosh** [comment]
Hello, what is this after?

> Поток <utils.blum.Start object at 0x0000024403A68380> | Ошибка: unsupported operand type(s) for /: 'NoneType' and 'int'

**Comment by MalinovyjMakintosh** [comment]
Updated the code, download the update
